routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['namespace' => 'Auth'], function () {
    Route::get('/login', 'LoginController@showLoginForm')->name('login.form');
    Route::post('/login', 'LoginController@login')->name('login');
    Route::post('/logout', 'LoginController@logout')->name('logout');
});

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    Route::get('/login', 'LoginController@showLoginForm')->name('login.form');
    Route::post('/login', 'LoginController@login')->name('login');
    Route::post('/logout', 'LoginController@logout')->name('logout');
});

//admin
Route::group(
    ['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.', 'middleware' => 'auth:web_admin'],
    function () {

        //users
        Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
            Route::get('/', 'UsersController@list')->name('list');
            Route::get('/create', 'UsersController@create')->name('create');
            Route::post('/store', 'UsersController@store')->name('store');
            Route::get('/edit/{id}', 'UsersController@edit')->name('edit');
            Route::put('/update/{id}', 'UsersController@update')->name('update');
            Route::delete('/delete/{id}', 'UsersController@delete')->name('delete');
        });

        //roles
        Route::group(['prefix' => 'roles', 'as' => 'roles.'], function () {
            Route::get('/', 'RoleController@list')->name('list');
            Route::get('/create', 'RoleController@create')->name('create');
            Route::post('/store', 'RoleController@store')->name('store');
            Route::get('/edit/{id}', 'RoleController@edit')->name('edit');
            Route::put('/update/{id}', 'RoleController@update')->name('update');
            Route::delete('/delete/{id}', 'RoleController@delete')->name('delete');
        });

        //units
        Route::group(['prefix' => 'units', 'as' => 'units.'], function () {
            Route::get('/', 'UnitController@list')->name('list');
            Route::get('/create', 'UnitController@create')->name('create');
            Route::post('/store', 'UnitController@store')->name('store');
            Route::get('/edit/{id}', 'UnitController@edit')->name('edit');
            Route::put('/update/{id}', 'UnitController@update')->name('update');
            Route::delete('/delete/{id}', 'UnitController@delete')->name('delete');

            //ajaxs
            Route::post('/roles', 'UnitController@rolesOfUnit');
        });

        //links
        Route::group(['prefix' => 'links', 'as' => 'links.'], function () {
            Route::get('/create', 'LinkController@create')->name('create');
            Route::post('/store', 'LinkController@store')->name('store');
            Route::get('/edit/{id}', 'LinkController@edit')->name('edit');
            Route::put('/update/{id}', 'LinkController@update')->name('update');
            Route::delete('/delete/{link}', 'LinkController@delete')->name('delete');
        });
    }
);

// find users
Route::group(
    ['prefix' => 'users', 'namespace' => 'Admin', 'as' => 'users.', 'middleware' => 'auth:web,web_admin'],
    function () {
        Route::post('/role', 'UsersController@findByRole')->name('role');
        Route::post('/unit', 'UsersController@findByUnit')->name('unit');
    }
);

Route::group(['middleware' => 'auth:web,web_admin'], function () {
    //dashboard
    Route::get('/', 'DashboardController@index')->name('dashboard');

    //affiches
    Route::group(['prefix' => 'affiches', 'namespace' => 'Affiche', 'as' => 'affiches.'], function () {
        Route::get('/list/{type?}', 'AfficheCommonController@list')->name('list');

        Route::post('/action-form/{id}/{action}', 'AfficheCommonController@actionForm')->name('action.form');
        Route::get('/action', 'AfficheCommonController@action')->name('action');
        Route::post('/accept/{id}', 'AfficheCommonController@accept')->name('accept');
        Route::post('/reject/{id}', 'AfficheCommonController@reject')->name('reject');
        Route::post('/user/affiches', 'AfficheCommonController@userAffiches')->name('user.affiches');

        Route::group(['as' => 'creator.'], function () {
            Route::get('/create/{type}', 'AfficheCreatorController@create')->name('create');
            Route::post('/store', 'AfficheCreatorController@store')->name('store');
            Route::get('/edit/{type}/{id}', 'AfficheCreatorController@edit')->name('edit');
            Route::put('/update/{id}', 'AfficheCreatorController@update')->name('update');
            Route::delete('/delete/{id}', 'AfficheCreatorController@delete')->name('delete');
            Route::post('/send/{id}', 'AfficheCreatorController@send')->name('send');
            Route::post('/archive/{id}', 'AfficheCreatorController@archive')->name('archive');
        });

        Route::group(['prefix' => 'contributors', 'as' => 'contributors.'], function () {
            Route::post('/list', 'AfficheContributorsController@list')->name('list');
        });

        Route::group(['prefix' => 'wares', 'as' => 'wares.'], function () {
            Route::post('/list/{affiche_type}/{affiche_id}', 'AfficheWaresController@list')->name('list');
            Route::get('/view', 'AfficheWaresController@view')->name('view');
            Route::get('/edit/{affiche_type}/{affiche_id}', 'AfficheWaresController@edit')->name('edit');
            Route::put('/update/{affiche_id}', 'AfficheWaresController@update')->name('update');
        });

        Route::group(['prefix' => 'alarms', 'as' => 'alarms.'], function () {
            Route::post('/clear', 'AfficheCommonController@clearAlarms')->name('clear');
        });
    });

    //messages
    Route::group(['prefix' => 'messages', 'namespace' => 'Message', 'as' => 'messages.'], function () {
        Route::get('/', 'MessageController@list')->name('list');
        Route::get('/create', 'MessageController@create')->name('create');
        Route::post('/store', 'MessageController@store')->name('store');
        Route::get('/edit/{id}', 'MessageController@edit')->name('edit');
        Route::put('/update/{id}', 'MessageController@update')->name('update');
        Route::delete('/delete/{id}', 'MessageController@delete')->name('delete');
    });

    //wares
    Route::group(['prefix' => 'wares', 'namespace' => 'Ware', 'as' => 'wares.'], function () {
        Route::get('/{type}', 'WaresController@list')->name('list');
        Route::get('/create/{type}', 'WaresController@create')->name('create');
        Route::post('/store', 'WaresController@store')->name('store');
        Route::get('/edit/{type}/{id}', 'WaresController@edit')->name('edit');
        Route::put('/update/{id}', 'WaresController@update')->name('update');
        Route::delete('/delete/{id}', 'WaresController@delete')->name('delete');
    });

    //categories
    Route::group([
        'prefix' => 'categories',
        'namespace' => 'Category',
        'as' => 'categories.',
        'middleware' => 'can:wares.create'
    ], function () {
        Route::get('/', 'CategoriesController@list')->name('list');
        Route::get('/create', 'CategoriesController@create')->name('create');
        Route::post('/store', 'CategoriesController@store')->name('store');
        Route::get('/edit/{category}', 'CategoriesController@edit')->name('edit');
        Route::put('/update/{category}', 'CategoriesController@update')->name('update');
        Route::delete('/delete/{category}', 'CategoriesController@delete')->name('delete');
    });

    //cars
    Route::group(['prefix' => 'cars', 'namespace' => 'Car', 'as' => 'cars.'], function () {
        Route::get('/', 'CarController@list')->name('list');
        Route::get('/create', 'CarController@create')->name('create');
        Route::post('/store', 'CarController@store')->name('store');
        Route::get('/edit/{car}', 'CarController@edit')->name('edit');
        Route::put('/update/{car}', 'CarController@update')->name('update');
        Route::delete('/delete/{car}', 'CarController@delete')->name('delete');
        Route::post('/search', 'CarController@search')->name('search');
    });

    //Links
    Route::get('/links', 'Link\\LinksController@list')->name('links.list');

    //Notifications
    Route::group([
        'prefix' => 'notifications',
        'namespace' => 'Notification',
        'as' => 'notification.'
    ], function () {
        Route::post('/list', 'NotificationController@list')->name('list');
        Route::post('/clear', 'NotificationController@clear')->name('clear');
    });
});

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    protected $fillable = ['name', 'slug', 'unit_id'];

    public $timestamps = false;

    public function admin()
    {
        return $this->hasOne(Admin::class);
    }

    public function users()
    {
        return $this->belongsToMany(User::class);
    }

    public function unit()
    {
        return $this->belongsTo(Unit::class);
    }

    public function affiches()
    {
        return $this->belongsToMany(Affiche::class);
    }
}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Role;
use App\Models\Unit;

class RoleController extends Controller
{
    public function list()
    {
        $roles = Role::with('unit')->get();
        return view('cp.role.list-role', compact('roles'));
    }

    public function create()
    {
        $units = Unit::all();

        if ($units->isEmpty()) {
            return back()->with('error', 'هیچ واحد خدمتی وجود ندارد! ابتدا یک واحد خدمتی ایجاد کنید.');
        }

        return view('cp.role.create-role', compact('units'));
    }

    public function store(Request $request)
    {
        $this->validateForm($request);

        $role = Role::create([
            'unit_id' => (int) $request['unit_id'],
            'name' => $request['name'],
            'slug' => $request['slug'],
        ]);

        if (!$role) {
            return redirect()->route('admin.roles.list')->with('error', 'در ایجاد نقش خطایی رخ داده است');
        }

        return redirect()->route('admin.roles.list')->with('success', 'نقش کاربری ایجاد شد');
    }

    public function edit($id)
    {
        $role = Role::with('unit')->find($id);

        $units = Unit::all();

        return view('cp.role.edit-role', compact('role', 'units'));
    }

    public function update(Request $request, $id)
    {
        $this->validateForm($request);

        $role = Role::find($id);

        $role->unit_id = $request->get('unit_id');
        $role->name = $request->get('name');
        $role->slug = $request->get('slug');
        $role->save();

        return redirect()->route('admin.roles.list')->with('success', 'نقش کاربری بروزرسانی شد');
    }

    public function delete($id)
    {
        $role = Role::find($id);
        $role->delete();
        return redirect()->route('admin.roles.list')->with('success', 'نقش کاربری حذف شد');
    }

    private function validateForm(Request $request)
    {
        $request->validate([
            'unit_id' => 'required',
            'name' => 'required|string|max:255',
            'slug' => 'required|string',
        ]);
    }
}

resources/views/cp/role/create-role.blade.php
@extends('layouts.multi-step-form')

@section('header')
<div class="card-header">
    <strong style="text-align:right;" class="card-header">{{ __('AuthFA.create_role') }}</strong>
</div>
@endsection

@section('form')
<form method="POST" action="{{ route('admin.roles.store') }}" class="multi-step">
    @csrf

    <div class="form-tab">
        <div class="form-group">
            <label style="float: right;">{{ __('AuthFA.role') }}</label>
            <input name="name" style="text-align:right;" type="text" class="form-control required" data-tag="input">
        </div>

        <div class="form-group">
            <label style="float: right;">{{ __('AuthFA.slug') }}</label>
            <input name="slug" style="text-align:right;" type="text" class="form-control required" data-tag="input">
        </div>

        <div class="form-group">
            <label style="float: right;">{{ __('AuthFA.unit_name') }}</label>
            <select name="unit_id" class="form-control select2-tag required"
                data-placeholder="{{ __('AuthFA.unit_modal_reg_message') }}" data-tag="select2">
                <option></option>
                @foreach($units as $unit)
                <option value="{{ $unit->id }}">{{ $unit->name }}</option>
                @endforeach
            </select>
        </div>
    </div>
    <div class="form-actions form-group ">
        <button type="button" class="btn btn-primary float-left" id="nextBtn">
            {{ __('AuthFA.create_role') }}
        </button>
        <a href="#" class="btn btn-secondary float-left mx-1" id="prevBtn">
            {{ __('AuthFA.back') }}
        </a>
    </div>
</form>
@endsection

resources/views/cp/role/edit-role.blade.php
@extends('layouts.multi-step-form')

@section('header')
<div class="card-header">
    <strong style="text-align:right;" class="card-header">{{ __('AuthFA.edit_role') }}</strong>
</div>
@endsection

@section('form')
<form method="POST" action="{{ route('admin.roles.update', [$role->id]) }}" class="multi-step">
    @csrf
    @method('PUT')

    <div class="form-tab">
        <div class="form-group">
            <label style="float: right;">{{ __('AuthFA.role') }}</label>
            <input name="name" style="text-align:right;" type="text" class="form-control" value="{{ $role->name }}">
        </div>

        <div class="form-group">
            <label style="float: right;">{{ __('AuthFA.slug') }}</label>
            <input name="slug" style="text-align:right;" type="text" class="form-control" value="{{ $role->slug }}">
        </div>

        <div class="form-group">
            <label style="float: right;">{{ __('AuthFA.unit_name') }}</label>
            <select name="unit_id" class="form-control" data-placeholder="{{ __('AuthFA.unit_modal_reg_message') }}">
                @foreach($units as $unit)
                <option value="{{ $unit->id }}" {{ $role->unit->id === $unit->id ? 'selected' : '' }}>
                    {{ $unit->name }}
                </option>
                @endforeach
            </select>
        </div>
    </div>
    <div class="form-actions form-group ">
        <button type="button" class="btn btn-primary float-left" id="nextBtn">
            {{ __('AuthFA.create_role') }}
        </button>
        <a href="#" class="btn btn-secondary float-left mx-1" id="prevBtn">
            {{ __('AuthFA.back') }}
        </a>
    </div>
</form>
@endsection

resources/views/cp/role/list-role.blade.php
@extends('layouts.tables')
@section('table-content')

<div class="content mt-3">
    <div class="animated fadeIn">
        <div class="row">

            <div class="col-md-12">
                <div class="card">

                    @include('partials.alerts')

                    <div class="card-header">
                        <strong class="card-title pull-right">{{ __('AuthFA.roles') }}</strong>
                        <a href="{{ route('admin.roles.create') }}"
                            class="btn btn-success pull-left">{{ __('AuthFA.create_role') }}</a>
                    </div>
                    <div class="card-body" style="overflow-x: auto">
                        <div class="row">
                            <dvi class="col-12 col-md-6 mb-3 mb-md-0">
                                <div class="input-group">
                                    <input type="text" class="form-control data-table-search-text"
                                        placeholder="جستجو..." data-table="#table1">
                                </div>
                            </dvi>
                            <div class="col-12 col-md-6">
                                <div class="form-group">
                                    <select class="form-control data-table-change-length ltr" data-table="#table1">
                                        <option selected>10</option>
                                        <option>20</option>
                                        <option>30</option>
                                        <option>40</option>
                                        <option>50</option>
                                    </select>
                                </div>
                            </div>
                        </div>

                        <table id="table1" class="table table-striped table-bordered bootstrap-data-table-export">
                            <thead>
                                <tr>
                                    <th>{{ __('AuthFA.row') }}</th>
                                    <th>{{ __('AuthFA.name') }}</th>
                                    <th>{{ __('AuthFA.slug') }}</th>
                                    <th>{{ __('AuthFA.unit_name') }}</th>
                                    <th>{{ __('AuthFA.operations') }}</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($roles as $i => $role)
                                <tr>
                                    <td>{{ ++$i }}</td>
                                    <td>{{ $role->name }}</td>
                                    <td>{{ $role->slug }}</td>
                                    <td><span
                                            class="badge badge-info">{{ $role->unit ? $role->unit->name : 'ندارد' }}</span>
                                    </td>
                                    <td class="d-flex flex-row">
                                        <a href="{{ route('admin.roles.edit', [$role->id]) }}"
                                            class="btn btn-sm rounded-circle btn-info">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        <form action="{{ route('admin.roles.delete', [$role->id]) }}" method="POST"
                                            class="mx-1">
                                            {{ method_field('DELETE') }}
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <button type="submit"
                                                class="btn btn-danger btn-sm rounded-circle deleteBtn">
                                                <i class="fas fa-trash"></i>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div><!-- .animated -->
</div><!-- .content -->

@endsection