routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['namespace' => 'Auth'], function () {
    Route::get('/login', 'LoginController@showLoginForm')->name('login.form');
    Route::post('/login', 'LoginController@login')->name('login');
    Route::post('/logout', 'LoginController@logout')->name('logout');
});

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    Route::get('/login', 'LoginController@showLoginForm')->name('login.form');
    Route::post('/login', 'LoginController@login')->name('login');
    Route::post('/logout', 'LoginController@logout')->name('logout');
});

//admin
Route::group(
    ['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.', 'middleware' => 'auth:web_admin'],
    function () {

        //users
        Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
            Route::get('/', 'UsersController@list')->name('list');
            Route::get('/create', 'UsersController@create')->name('create');
            Route::post('/store', 'UsersController@store')->name('store');
            Route::get('/edit/{id}', 'UsersController@edit')->name('edit');
            Route::put('/update/{id}', 'UsersController@update')->name('update');
            Route::delete('/delete/{id}', 'UsersController@delete')->name('delete');
        });

        //roles
        Route::group(['prefix' => 'roles', 'as' => 'roles.'], function () {
            Route::get('/', 'RoleController@list')->name('list');
            Route::get('/create', 'RoleController@create')->name('create');
            Route::post('/store', 'RoleController@store')->name('store');
            Route::get('/edit/{id}', 'RoleController@edit')->name('edit');
            Route::put('/update/{id}', 'RoleController@update')->name('update');
            Route::delete('/delete/{id}', 'RoleController@delete')->name('delete');
        });

        //units
        Route::group(['prefix' => 'units', 'as' => 'units.'], function () {
            Route::get('/', 'UnitController@list')->name('list');
            Route::get('/create', 'UnitController@create')->name('create');
            Route::post('/store', 'UnitController@store')->name('store');
            Route::get('/edit/{id}', 'UnitController@edit')->name('edit');
            Route::put('/update/{id}', 'UnitController@update')->name('update');
            Route::delete('/delete/{id}', 'UnitController@delete')->name('delete');

            //ajaxs
            Route::post('/roles', 'UnitController@rolesOfUnit');
        });

        //links
        Route::group(['prefix' => 'links', 'as' => 'links.'], function () {
            Route::get('/create', 'LinkController@create')->name('create');
            Route::post('/store', 'LinkController@store')->name('store');
            Route::get('/edit/{id}', 'LinkController@edit')->name('edit');
            Route::put('/update/{id}', 'LinkController@update')->name('update');
            Route::delete('/delete/{link}', 'LinkController@delete')->name('delete');
        });
    }
);

// find users
Route::group(
    ['prefix' => 'users', 'namespace' => 'Admin', 'as' => 'users.', 'middleware' => 'auth:web,web_admin'],
    function () {
        Route::post('/role', 'UsersController@findByRole')->name('role');
        Route::post('/unit', 'UsersController@findByUnit')->name('unit');
    }
);

Route::group(['middleware' => 'auth:web,web_admin'], function () {
    //dashboard
    Route::get('/', 'DashboardController@index')->name('dashboard');

    //affiches
    Route::group(['prefix' => 'affiches', 'namespace' => 'Affiche', 'as' => 'affiches.'], function () {
        Route::get('/list/{type?}', 'AfficheCommonController@list')->name('list');

        Route::post('/action-form/{id}/{action}', 'AfficheCommonController@actionForm')->name('action.form');
        Route::get('/action', 'AfficheCommonController@action')->name('action');
        Route::post('/accept/{id}', 'AfficheCommonController@accept')->name('accept');
        Route::post('/reject/{id}', 'AfficheCommonController@reject')->name('reject');
        Route::post('/user/affiches', 'AfficheCommonController@userAffiches')->name('user.affiches');

        Route::group(['as' => 'creator.'], function () {
            Route::get('/create/{type}', 'AfficheCreatorController@create')->name('create');
            Route::post('/store', 'AfficheCreatorController@store')->name('store');
            Route::get('/edit/{type}/{id}', 'AfficheCreatorController@edit')->name('edit');
            Route::put('/update/{id}', 'AfficheCreatorController@update')->name('update');
            Route::delete('/delete/{id}', 'AfficheCreatorController@delete')->name('delete');
            Route::post('/send/{id}', 'AfficheCreatorController@send')->name('send');
            Route::post('/archive/{id}', 'AfficheCreatorController@archive')->name('archive');
        });

        Route::group(['prefix' => 'contributors', 'as' => 'contributors.'], function () {
            Route::post('/list', 'AfficheContributorsController@list')->name('list');
        });

        Route::group(['prefix' => 'wares', 'as' => 'wares.'], function () {
            Route::post('/list/{affiche_type}/{affiche_id}', 'AfficheWaresController@list')->name('list');
            Route::get('/view', 'AfficheWaresController@view')->name('view');
            Route::get('/edit/{affiche_type}/{affiche_id}', 'AfficheWaresController@edit')->name('edit');
            Route::put('/update/{affiche_id}', 'AfficheWaresController@update')->name('update');
        });

        Route::group(['prefix' => 'alarms', 'as' => 'alarms.'], function () {
            Route::post('/clear', 'AfficheCommonController@clearAlarms')->name('clear');
        });
    });

    //messages
    Route::group(['prefix' => 'messages', 'namespace' => 'Message', 'as' => 'messages.'], function () {
        Route::get('/', 'MessageController@list')->name('list');
        Route::get('/create', 'MessageController@create')->name('create');
        Route::post('/store', 'MessageController@store')->name('store');
        Route::get('/edit/{id}', 'MessageController@edit')->name('edit');
        Route::put('/update/{id}', 'MessageController@update')->name('update');
        Route::delete('/delete/{id}', 'MessageController@delete')->name('delete');
    });

    //wares
    Route::group(['prefix' => 'wares', 'namespace' => 'Ware', 'as' => 'wares.'], function () {
        Route::get('/{type}', 'WaresController@list')->name('list');
        Route::get('/create/{type}', 'WaresController@create')->name('create');
        Route::post('/store', 'WaresController@store')->name('store');
        Route::get('/edit/{type}/{id}', 'WaresController@edit')->name('edit');
        Route::put('/update/{id}', 'WaresController@update')->name('update');
        Route::delete('/delete/{id}', 'WaresController@delete')->name('delete');
    });

    //categories
    Route::group([
        'prefix' => 'categories',
        'namespace' => 'Category',
        'as' => 'categories.',
        'middleware' => 'can:wares.create'
    ], function () {
        Route::get('/', 'CategoriesController@list')->name('list');
        Route::get('/create', 'CategoriesController@create')->name('create');
        Route::post('/store', 'CategoriesController@store')->name('store');
        Route::get('/edit/{category}', 'CategoriesController@edit')->name('edit');
        Route::put('/update/{category}', 'CategoriesController@update')->name('update');
        Route::delete('/delete/{category}', 'CategoriesController@delete')->name('delete');
    });

    //cars
    Route::group(['prefix' => 'cars', 'namespace' => 'Car', 'as' => 'cars.'], function () {
        Route::get('/', 'CarController@list')->name('list');
        Route::get('/create', 'CarController@create')->name('create');
        Route::post('/store', 'CarController@store')->name('store');
        Route::get('/edit/{car}', 'CarController@edit')->name('edit');
        Route::put('/update/{car}', 'CarController@update')->name('update');
        Route::delete('/delete/{car}', 'CarController@delete')->name('delete');
        Route::post('/search', 'CarController@search')->name('search');
    });

    //Links
    Route::get('/links', 'Link\\LinksController@list')->name('links.list');

    //Notifications
    Route::group([
        'prefix' => 'notifications',
        'namespace' => 'Notification',
        'as' => 'notification.'
    ], function () {
        Route::post('/list', 'NotificationController@list')->name('list');
        Route::post('/clear', 'NotificationController@clear')->name('clear');
    });
});

app/Models/Link.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Link extends Model
{
    protected $fillable = ['name', 'url', 'status'];
}

app/Http/Controllers/Admin/LinkController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Link\LinkCreateRequest;
use App\Models\Link;

class LinkController extends Controller
{

    public function create()
    {
        return view('cp.link.create-link');
    }

    public function store(LinkCreateRequest $request)
    {
        $link = Link::create([
            'name' => $request['name'],
            'url' => $request['url'],
            'status' =>  $request['status'],
        ]);

        if (!($link instanceof Link)) {
            return redirect()->route('links.list')->with('error', 'خطایی رخ داده است!');
        }

        return redirect()->route('links.list')->with('success', 'پیوند ایجاد شد');
    }

    public function edit($id)
    {
        $link = Link::findOrFail($id);

        return view('cp.link.edit-link', compact('link'));
    }

    public function update(LinkCreateRequest $request, $id)
    {
        $link = Link::findOrFail($id);

        $link->name = $request->get('name');
        $link->url = $request->get('url');
        $link->status = $request->get('status');

        $result = $link->save();

        if (!$result) {
            return redirect()->route('links.list')->with('error', 'خطایی رخ داده است!');
        }

        return redirect()->route('links.list')->with('success', 'پیوند بروزرسانی شد');
    }

    public function delete(Link $link)
    {
        $result = $link->delete();

        if (!$result) {
            return redirect()->route('links.list')->with('error', 'خطایی رخ داده است!');
        }

        return redirect()->route('links.list')->with('success', 'پیوند حذف شد');
    }
}

app/Http/Controllers/Link/LinksController.php
<?php

namespace App\Http\Controllers\Link;

use App\Models\Link;
use App\Http\Controllers\Controller;

class LinksController extends Controller
{
    public function list()
    {
        $links = Link::all();

        return view('cp.link.list-link', compact('links'));
    }
}

resources/views/cp/link/create-link.blade.php
@extends('layouts.multi-step-form')

@section('header')
<div class="card-header">
    <strong style="text-align:right;" class="card-header">{{ __('AuthFA.create_link') }}</strong>
</div>
@endsection

@section('form')

<form method="POST" action="{{ route('admin.links.store') }}" class="multi-step">
    @csrf

    <div class="form-tab">
        <div class="form-group">
            <label>{{ __('AuthFA.link_name') }}</label>
            <input name="name" type="text" class="form-control required" data-tag="input">
        </div>

        <div class="form-group">
            <label>{{ __('AuthFA.link_url') }}</label>
            <input name="url" type="text" class="form-control required" data-tag="input">
        </div>

        <div class="form-group">
            <label>{{ __('AuthFA.status') }}</label>
            <select name="status" class="form-control select2-tag" data-tag="select2"
                data-placeholder="{{ __('AuthFA.status') }}">
                <option></option>
                <option value="1">{{ __('AuthFA.active') }}</option>
                <option value="0">{{ __('AuthFA.deactive') }}</option>
            </select>
        </div>
    </div>

    <div class="form-actions form-group ">
        <button type="button" class="btn btn-primary float-left" id="nextBtn">
            {{ __('AuthFA.create_link') }}
        </button>
        <a href="#" class="btn btn-secondary float-left mx-1" id="prevBtn">
            {{ __('AuthFA.back') }}
        </a>
    </div>
</form>

@endsection

resources/views/cp/link/edit-link.blade.php
@extends('layouts.multi-step-form')

@section('header')
<div class="card-header">
    <strong style="text-align:right;" class="card-header">{{ __('AuthFA.edit_link') }}</strong>
</div>
@endsection

@section('form')

<form method="POST" action="{{ route('admin.links.update', [$link->id]) }}" class="multi-step">
    @csrf
    @method('PUT')

    <div class="form-tab">
        <div class="form-group">
            <label>{{ __('AuthFA.link_name') }}</label>
            <input name="name" type="text" class="form-control required" data-tag="input" value="{{ $link->name }}">
        </div>

        <div class="form-group">
            <label>{{ __('AuthFA.link_url') }}</label>
            <input name="url" type="text" class="form-control required" data-tag="input" value="{{ $link->url }}">
        </div>

        <div class="form-group">
            <label>{{ __('AuthFA.status') }}</label>
            <select name="status" class="form-control select2-tag" data-tag="select2"
                data-placeholder="{{ __('AuthFA.status') }}">
                <option></option>
                <option value="1" {{ ((int) $link->status) === 1 ? 'selected' : '' }}>
                    {{ __('AuthFA.active') }}
                </option>
                <option value="0" {{ ((int) $link->status) === 0 ? 'selected' : '' }}>
                    {{ __('AuthFA.deactive') }}
                </option>
            </select>
        </div>
    </div>

    <div class="form-actions form-group ">
        <button type="button" class="btn btn-primary float-left" id="nextBtn">
            {{ __('AuthFA.edit_link') }}
        </button>
        <a href="#" class="btn btn-secondary float-left mx-1" id="prevBtn">
            {{ __('AuthFA.back') }}
        </a>
    </div>
</form>

@endsection

resources/views/cp/link/list-link.blade.php
@extends('layouts.tables')
@section('table-content')

<div class="content mt-3">
    <div class="animated fadeIn">
        <div class="row">

            <div class="col-md-12">
                <div class="card">

                    @include('partials.alerts')

                    <div class="card-header">
                        <strong class="card-title pull-right">{{ __('AuthFA.links') }}</strong>
                        @admin
                        <a href="{{ route('admin.links.create') }}" class="btn btn-success pull-left">
                            {{ __('AuthFA.create_link') }}
                        </a>
                        @endadmin
                    </div>

                    <div class="card-body" style="overflow-x: auto">
                        <div class="row">
                            <dvi class="col-12 col-md-6 mb-3 mb-md-0">
                                <div class="input-group">
                                    <input type="text" class="form-control data-table-search-text"
                                        placeholder="جستجو..." data-table="#table1">
                                </div>
                            </dvi>
                            <div class="col-12 col-md-6">
                                <div class="form-group">
                                    <select class="form-control data-table-change-length ltr" data-table="#table1">
                                        <option selected>10</option>
                                        <option>20</option>
                                        <option>30</option>
                                        <option>40</option>
                                        <option>50</option>
                                    </select>
                                </div>
                            </div>
                        </div>

                        <table id="table1" class="table table-striped table-bordered bootstrap-data-table-export">
                            <thead>
                                <tr class="text-center">
                                    <th>{{ __('AuthFA.row') }}</th>
                                    <th>{{ __('AuthFA.link_name') }}</th>
                                    <th>{{ __('AuthFA.link_url') }}</th>
                                    <th>{{ __('AuthFA.status') }}</th>
                                    @admin
                                    <th>{{ __('AuthFA.operations') }}</th>
                                    @endadmin
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($links as $i => $link)
                                <tr class="text-center">
                                    <td>{{ ++$i }}</td>
                                    <td>{{ $link->name }}</td>
                                    <td>
                                        @if ($link->status == 1)
                                        <a class="font-weight-bold text-info" href="{{ $link->url }}"
                                            target="{{ $link->url }}">
                                            {{ $link->url }}
                                        </a>
                                        @else
                                        <span>{{ $link->url }}</span>
                                        @endif
                                    </td>
                                    <td>
                                        @if ($link->status == 1)
                                        <span class="badge badge-success mx-1">
                                            {{ __('AuthFA.active') }}
                                        </span>
                                        @else
                                        <span class="badge badge-danger mx-1">
                                            {{ __('AuthFA.deactive') }}
                                        </span>
                                        @endif
                                    </td>
                                    @admin
                                    <td class="d-flex flex-row justify-content-center">
                                        <a href="{{ route('admin.links.edit', [$link->id]) }}"
                                            class="btn btn-sm btn-info rounded-circle">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        <form action="{{ route('admin.links.delete', [$link->id]) }}" method="POST"
                                            class="mx-1">
                                            {{ method_field('DELETE') }}
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <button type="submit"
                                                class="btn btn-danger btn-sm rounded-circle deleteBtn">
                                                <i class="fas fa-trash"></i>
                                            </button>
                                        </form>
                                    </td>
                                    @endadmin
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div><!-- .animated -->
</div><!-- .content -->

@endsection