routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['namespace' => 'Auth'], function () {
    Route::get('/login', 'LoginController@showLoginForm')->name('login.form');
    Route::post('/login', 'LoginController@login')->name('login');
    Route::post('/logout', 'LoginController@logout')->name('logout');
});

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {
    Route::get('/login', 'LoginController@showLoginForm')->name('login.form');
    Route::post('/login', 'LoginController@login')->name('login');
    Route::post('/logout', 'LoginController@logout')->name('logout');
});

//admin
Route::group(
    ['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.', 'middleware' => 'auth:web_admin'],
    function () {

        //users
        Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
            Route::get('/', 'UsersController@list')->name('list');
            Route::get('/create', 'UsersController@create')->name('create');
            Route::post('/store', 'UsersController@store')->name('store');
            Route::get('/edit/{id}', 'UsersController@edit')->name('edit');
            Route::put('/update/{id}', 'UsersController@update')->name('update');
            Route::delete('/delete/{id}', 'UsersController@delete')->name('delete');
        });

        //roles
        Route::group(['prefix' => 'roles', 'as' => 'roles.'], function () {
            Route::get('/', 'RoleController@list')->name('list');
            Route::get('/create', 'RoleController@create')->name('create');
            Route::post('/store', 'RoleController@store')->name('store');
            Route::get('/edit/{id}', 'RoleController@edit')->name('edit');
            Route::put('/update/{id}', 'RoleController@update')->name('update');
            Route::delete('/delete/{id}', 'RoleController@delete')->name('delete');
        });

        //units
        Route::group(['prefix' => 'units', 'as' => 'units.'], function () {
            Route::get('/', 'UnitController@list')->name('list');
            Route::get('/create', 'UnitController@create')->name('create');
            Route::post('/store', 'UnitController@store')->name('store');
            Route::get('/edit/{id}', 'UnitController@edit')->name('edit');
            Route::put('/update/{id}', 'UnitController@update')->name('update');
            Route::delete('/delete/{id}', 'UnitController@delete')->name('delete');

            //ajaxs
            Route::post('/roles', 'UnitController@rolesOfUnit');
        });

        //links
        Route::group(['prefix' => 'links', 'as' => 'links.'], function () {
            Route::get('/create', 'LinkController@create')->name('create');
            Route::post('/store', 'LinkController@store')->name('store');
            Route::get('/edit/{id}', 'LinkController@edit')->name('edit');
            Route::put('/update/{id}', 'LinkController@update')->name('update');
            Route::delete('/delete/{link}', 'LinkController@delete')->name('delete');
        });
    }
);

// find users
Route::group(
    ['prefix' => 'users', 'namespace' => 'Admin', 'as' => 'users.', 'middleware' => 'auth:web,web_admin'],
    function () {
        Route::post('/role', 'UsersController@findByRole')->name('role');
        Route::post('/unit', 'UsersController@findByUnit')->name('unit');
    }
);

Route::group(['middleware' => 'auth:web,web_admin'], function () {
    //dashboard
    Route::get('/', 'DashboardController@index')->name('dashboard');

    //affiches
    Route::group(['prefix' => 'affiches', 'namespace' => 'Affiche', 'as' => 'affiches.'], function () {
        Route::get('/list/{type?}', 'AfficheCommonController@list')->name('list');

        Route::post('/action-form/{id}/{action}', 'AfficheCommonController@actionForm')->name('action.form');
        Route::get('/action', 'AfficheCommonController@action')->name('action');
        Route::post('/accept/{id}', 'AfficheCommonController@accept')->name('accept');
        Route::post('/reject/{id}', 'AfficheCommonController@reject')->name('reject');
        Route::post('/user/affiches', 'AfficheCommonController@userAffiches')->name('user.affiches');

        Route::group(['as' => 'creator.'], function () {
            Route::get('/create/{type}', 'AfficheCreatorController@create')->name('create');
            Route::post('/store', 'AfficheCreatorController@store')->name('store');
            Route::get('/edit/{type}/{id}', 'AfficheCreatorController@edit')->name('edit');
            Route::put('/update/{id}', 'AfficheCreatorController@update')->name('update');
            Route::delete('/delete/{id}', 'AfficheCreatorController@delete')->name('delete');
            Route::post('/send/{id}', 'AfficheCreatorController@send')->name('send');
            Route::post('/archive/{id}', 'AfficheCreatorController@archive')->name('archive');
        });

        Route::group(['prefix' => 'contributors', 'as' => 'contributors.'], function () {
            Route::post('/list', 'AfficheContributorsController@list')->name('list');
        });

        Route::group(['prefix' => 'wares', 'as' => 'wares.'], function () {
            Route::post('/list/{affiche_type}/{affiche_id}', 'AfficheWaresController@list')->name('list');
            Route::get('/view', 'AfficheWaresController@view')->name('view');
            Route::get('/edit/{affiche_type}/{affiche_id}', 'AfficheWaresController@edit')->name('edit');
            Route::put('/update/{affiche_id}', 'AfficheWaresController@update')->name('update');
        });

        Route::group(['prefix' => 'alarms', 'as' => 'alarms.'], function () {
            Route::post('/clear', 'AfficheCommonController@clearAlarms')->name('clear');
        });
    });

    //messages
    Route::group(['prefix' => 'messages', 'namespace' => 'Message', 'as' => 'messages.'], function () {
        Route::get('/', 'MessageController@list')->name('list');
        Route::get('/create', 'MessageController@create')->name('create');
        Route::post('/store', 'MessageController@store')->name('store');
        Route::get('/edit/{id}', 'MessageController@edit')->name('edit');
        Route::put('/update/{id}', 'MessageController@update')->name('update');
        Route::delete('/delete/{id}', 'MessageController@delete')->name('delete');
    });

    //wares
    Route::group(['prefix' => 'wares', 'namespace' => 'Ware', 'as' => 'wares.'], function () {
        Route::get('/{type}', 'WaresController@list')->name('list');
        Route::get('/create/{type}', 'WaresController@create')->name('create');
        Route::post('/store', 'WaresController@store')->name('store');
        Route::get('/edit/{type}/{id}', 'WaresController@edit')->name('edit');
        Route::put('/update/{id}', 'WaresController@update')->name('update');
        Route::delete('/delete/{id}', 'WaresController@delete')->name('delete');
    });

    //categories
    Route::group([
        'prefix' => 'categories',
        'namespace' => 'Category',
        'as' => 'categories.',
        'middleware' => 'can:wares.create'
    ], function () {
        Route::get('/', 'CategoriesController@list')->name('list');
        Route::get('/create', 'CategoriesController@create')->name('create');
        Route::post('/store', 'CategoriesController@store')->name('store');
        Route::get('/edit/{category}', 'CategoriesController@edit')->name('edit');
        Route::put('/update/{category}', 'CategoriesController@update')->name('update');
        Route::delete('/delete/{category}', 'CategoriesController@delete')->name('delete');
    });

    //cars
    Route::group(['prefix' => 'cars', 'namespace' => 'Car', 'as' => 'cars.'], function () {
        Route::get('/', 'CarController@list')->name('list');
        Route::get('/create', 'CarController@create')->name('create');
        Route::post('/store', 'CarController@store')->name('store');
        Route::get('/edit/{car}', 'CarController@edit')->name('edit');
        Route::put('/update/{car}', 'CarController@update')->name('update');
        Route::delete('/delete/{car}', 'CarController@delete')->name('delete');
        Route::post('/search', 'CarController@search')->name('search');
    });

    //Links
    Route::get('/links', 'Link\\LinksController@list')->name('links.list');

    //Notifications
    Route::group([
        'prefix' => 'notifications',
        'namespace' => 'Notification',
        'as' => 'notification.'
    ], function () {
        Route::post('/list', 'NotificationController@list')->name('list');
        Route::post('/clear', 'NotificationController@clear')->name('clear');
    });
});

app/Models/Car.php
<?php

namespace App\Models;

use App\Models\Affiches\CarAffiche;
use Illuminate\Database\Eloquent\Model;

class Car extends Model
{
    protected $guarded = ['id'];

    public function affiche()
    {
        return $this->belongsTo(CarAffiche::class, 'affiche_id');
    }

    public function driver()
    {
        return $this->belongsTo(User::class, 'driver_id');
    }
}

app/Http/Controllers/Car/CarController.php
<?php

namespace App\Http\Controllers\Car;

use App\Models\Car;
use Illuminate\Http\Request;
use App\Services\Car\CarService;
use App\Http\Controllers\Controller;
use App\Http\Requests\Car\CarRequest;

class CarController extends Controller
{

    private $carService;

    public function __construct(CarService $carService)
    {
        $this->carService = $carService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function list()
    {
        $cars = $this->carService->all();

        return view('cp.car.list-car', compact('cars'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cp.car.create-car');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  CarRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CarRequest $request)
    {
        $category = Car::create([
            'plate_number' => $request->input('plate'),
            'name' => $request->input('name'),
            'description' => $request->input('description')
        ]);

        if (!($category instanceof Car)) {
            return redirect()->route('cars.list')->with('error', 'در ایجاد خودرو خطایی رخ داده است.');
        }

        return redirect()->route('cars.list')->with('success', 'خودرو با موفقیت ایجاد شد.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Car  $car
     * @return \Illuminate\View\View
     */
    public function edit(Car $car)
    {
        list($left, $word, $right, $state) = explode('-', $car->plate_number);

        $car->plate_number = [
            'left' => $left,
            'right' => $right,
            'word' => $word,
            'state' => $state
        ];

        return view('cp.car.edit-car', compact('car'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  CarRequest  $request
     * @param  Car  $car
     * @return
     */
    public function update(Car $car, CarRequest $request)
    {
        $result = $car->update([
            'plate_number' => $request->input('plate'),
            'name' => $request->input('name'),
            'description' => $request->input('description')
        ]);

        if (!$result) {
            return redirect()->route('cars.list')->with('error', 'در بروزرسانی خودرو خطایی رخ داده است.');
        }

        return redirect()->route('cars.list')->with('success', 'خودرو با موفقیت بروزرسانی شد.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Car  $car
     * @return
     */
    public function delete(Car $car)
    {
        $result = $car->delete();

        if (!$result) {
            return redirect()->route('cars.list')->with('error', 'در حذف خودرو خطایی رخ داده است.');
        }

        return redirect()->route('cars.list')->with('success', 'خودرو با موفقیت حذف شد.');
    }

    public function search(Request $request)
    {
        $search = $request['search'] ?? null;

        $cars = $this->carService->find($search, true, ['id', 'name', 'plate_number']);

        return response()->json($cars);
    }
}

resources/views/cp/car/create-car.blade.php
@extends('layouts.multi-step-form')

@section('header')
<div class="card-header">
    <strong style="text-align:right;" class="card-header">{{ __('labels.car.create_title') }}</strong>
</div>
@endsection

@section('form')
<form method="POST" action="{{ route('cars.store') }}" class="multi-step">
    @csrf

    <div class="form-tab">
        <div class="form-group">
            <label style="float: right;">{{ __('labels.car.plate') }}</label>
            <div class="plate-number rounded" x-data="plateNumber()">
                <input name="plate_state" type="number" min="10" max="99" class="plate-input plate-state"
                    x-model="plateState">
                <input name="plate_right" type="number" min="100" max="999" class="plate-input plate-right"
                    x-model="plateRight">
                <select name="plate_word" class="plate-word" x-model="plateWord">
                    @foreach(__('labels.car.plate_word') as $key => $word)
                    <option {{ $word=='الف' ? 'selected' : '' }} value="{{ $key }}">{{ $word }}</option>
                    @endforeach
                </select>
                <input type="number" name="plate_left" min="10" max="99" class="plate-input plate-left"
                    x-model="plateLeft">
                <input type="hidden" name="plate" :value="plate()">
            </div>
        </div>

        <div class="form-group">
            <label style="float: right;">{{ __('labels.car.name') }}</label>
            <input name="name" type="text" class="form-control required" data-tag="input">
        </div>
        <div class="form-group">
            <label style="float: right;">{{ __('labels.car.description') }}</label>
            <textarea name="description" class="form-control" data-tag="input"></textarea>
        </div>
    </div>
    <div class="form-actions form-group ">
        <button type="button" class="btn btn-primary float-left" id="nextBtn">
            ثبت
        </button>
        <a href="#" class="btn btn-secondary float-left mx-1" id="prevBtn">
            بازگشت
        </a>
    </div>
</form>
@endsection

@push('form-scripts')
<script>
    const plateNumber = () => {
        return {
            plateLeft: '',
            plateRight: '',
            plateWord: '',
            plateState: '',

            plate() {
                return `${this.plateLeft}-${this.plateWord}-${this.plateRight}-${this.plateState}`
            }
        }
    }
</script>
@endpush

resources/views/cp/car/edit-car.blade.php
@extends('layouts.multi-step-form')

@section('header')
<div class="card-header">
    <strong style="text-align:right;" class="card-header">{{ __('labels.car.update_title') }}</strong>
</div>
@endsection

@section('form')
<form method="POST" action="{{ route('cars.update', [$car->id]) }}" class="multi-step">
    @csrf
    @method('PUT')

    <div class="form-tab">
        <div class="form-group">
            <label style="float: right;">{{ __('labels.car.plate') }}</label>
            <div class="plate-number rounded" x-data="plateNumber()">
                <input name="plate_state" type="number" min="10" max="99" class="plate-input plate-state"
                    x-model="plateState">
                <input name="plate_right" type="number" min="100" max="999" class="plate-input plate-right"
                    x-model="plateRight">
                <select name="plate_word" class="plate-word" x-model="plateWord">
                    @foreach(__('labels.car.plate_word') as $key => $word)
                    <option {{ $key==$car['plate_number']['word'] ? 'selected' : '' }} value="{{ $key }}">
                        {{$word }}
                    </option>
                    @endforeach
                </select>
                <input type="number" name="plate_left" min="10" max="99" class="plate-input plate-left"
                    x-model="plateLeft">
                <input type="hidden" name="plate" :value="plate()">
            </div>
        </div>

        <div class="form-group">
            <label style="float: right;">{{ __('labels.car.name') }}</label>
            <input name="name" type="text" class="form-control required" data-tag="input" value="{{ $car->name }}">
        </div>
        <div class="form-group">
            <label style="float: right;">{{ __('labels.car.description') }}</label>
            <textarea name="description" class="form-control" data-tag="input"
                value="{{ $car->description }}"></textarea>
        </div>
    </div>
    <div class="form-actions form-group ">
        <button type="button" class="btn btn-primary float-left" id="nextBtn">
            ثبت
        </button>
        <a href="#" class="btn btn-secondary float-left mx-1" id="prevBtn">
            بازگشت
        </a>
    </div>
</form>
@endsection

@push('form-scripts')
<script>
    const plateNumber = () => {
        return {
            plateLeft: "{{ $car['plate_number']['left'] }}",
            plateRight: "{{ $car['plate_number']['right'] }}",
            plateWord: "{{ $car['plate_number']['word'] }}",
            plateState: "{{ $car['plate_number']['state'] }}",

            plate() {
                return `${this.plateLeft}-${this.plateWord}-${this.plateRight}-${this.plateState}`
            }
        }
    }
</script>
@endpush

resources/views/cp/car/list-car.blade.php
@extends('layouts.tables')

@section('table-content')

<div class="content mt-3">
    <div class="animated fadeIn">
        <div class="row">

            <div class="col-md-12">
                <div class="card">

                    @include('partials.alerts')

                    <div class="card-header">
                        <strong class="card-title pull-right">{{ __('labels.car.list_title') }}</strong>
                        <a href="{{ route('cars.create') }}" class="btn btn-success pull-left">{{
                            __('labels.car.create_title') }}</a>
                    </div>
                    <div class="card-body" style="overflow-x: auto">
                        <div class="row">
                            <dvi class="col-12 col-md-6 mb-3 mb-md-0">
                                <div class="input-group">
                                    <input type="text" class="form-control data-table-search-text"
                                        placeholder="جستجو..." data-table="#table1">
                                </div>
                            </dvi>
                            <div class="col-12 col-md-6">
                                <div class="form-group">
                                    <select class="form-control data-table-change-length ltr" data-table="#table1">
                                        <option selected>10</option>
                                        <option>20</option>
                                        <option>30</option>
                                        <option>40</option>
                                        <option>50</option>
                                    </select>
                                </div>
                            </div>
                        </div>

                        <table id="table1" class="table table-striped table-bordered bootstrap-data-table-export">
                            <thead>
                                <tr>
                                    <th>{{ __('labels.generals.row') }}</th>
                                    <th>{{ __('labels.car.name') }}</th>
                                    <th>{{ __('labels.car.plate') }}</th>
                                    <th>{{ __('labels.car.driver') }}</th>
                                    <th>{{ __('labels.car.affiche') }}</th>
                                    <th>{{ __('labels.generals.operations') }}</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($cars as $i => $car)
                                <tr>
                                    <td>{{ ++$i }}</td>
                                    <td>{{ $car->name }}</td>
                                    <td>{{ $car->plate_number }}</td>
                                    <td>{{ ($car['driver']->name ?? '-') . ($car['driver']->family_name ?? '-') }}</td>
                                    <td>{{ $car['affiche']->name ?? '--' }}</td>
                                    <td class="d-flex flex-row">
                                        <a href="{{ route('cars.edit', [$car->id]) }}"
                                            class="btn btn-sm rounded-circle btn-info">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                        <form action="{{ route('cars.delete', [$car->id]) }}" method="POST"
                                            class="mx-1">
                                            {{ method_field('DELETE') }}
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <button type="submit"
                                                class="btn btn-danger btn-sm rounded-circle deleteBtn">
                                                <i class="fas fa-trash"></i>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div><!-- .animated -->
</div><!-- .content -->

@endsection